version: "3"

services:
#--------------------------------------------------------------------------#
#--------------------------------------------------------------------------#
#                           S C A L A JDK v8                               #
#--------------------------------------------------------------------------#
#--------------------------------------------------------------------------#
  ubuntu:
      build: ./
      image: scala_jdk8
      container_name: 'scala'
      restart: always
      volumes: 
        - ./Oberon:/home/Oberon
        